# Generated by Django 5.1.1 on 2025-11-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='occupation',
            field=models.CharField(default='Unknown', max_length=80),
        ),
    ]
